"$schema" = "https://starship.rs/config-schema.json"

# THEME  
format = """
[╭─](lq)\
[](def_purple)\
$os\
$username\
[](fg:def_purple bg:lc_purple)\
$directory\
[](fg:lc_blue bg:def_mint)\
$git_branch\
[](fg:def_mint bg:lc_green)\
$shell\
[](fg:lc_green bg:def_yellow)\
$cmd_duration\
[](def_yellow)\
$fill\
[](lc)\
$status\
[](fg:def_orange bg:lc)\
$memory_usage\
[](fg:lc_red bg:def_orange)\
${custom.directory}\
[](fg:def_pink bg:lc_red)\
$time\
[](def_pink)\
[─╮](lq)\
$line_breat
[╰─](lq)\
$character"""

right_format = """
[❯](lq)\
[─╯](lq)\
"""

# COLORS
palette = "CodemosModernDark"
[palettes.CodemosModernDark]
lc = "#333333"
lq = "#444444"
hc = "#cccccc"
hq = "#dddddd"

def_brown = "#CB8569"
def_red = "#ef6363"
def_orange = "#D28342"
def_yellow = "#bfaf40"
def_green = "#45AA41"
def_mint = "#46A598"
def_blue = "#4B9ECD"
def_purple = "#9B87EA"
def_pink = "#ED63BA"

alt_red = "#d19797"
alt_orange = "#c59e7f"
alt_yellow = "#ada77f"
alt_green = "#80b27f"
alt_mint = "#83aea8"
alt_blue = "#87abc0"
alt_purple = "#a9a0cb"
alt_pink = "#cd95b8"

lc_red = "#3a2727"
lc_orange = "#322b24"
lc_yellow = "#343327"
lc_green = "#273027"
lc_mint = "#27302f"
lc_blue = "#252d31"
lc_purple = "#2e2a3c"
lc_pink = "#3a2733"

# LEFT ALIGNED PROMPT

[os]
style = "fg:lc_purple bg:def_purple"
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Fedora = "󰣛 "

[username]
show_always = true
style_user = "fg:lc_purple bg:def_purple"
style_root = "fg:lc_purple bg:def_purple"
format = "[󱕆 󰀄 ]($style)"
disabled = true

[directory]
style = "fg:alt_blue bg:lc_blue"
repo_root_style = "fg:def_blue bg:lc_blue"
read_only = ""
read_only_style = "fg:def_red bg:lc_blue"
format = """
[ $path ]($style)\
([]($style)[ $read_only ]($read_only_style))"""
repo_root_format = """
[  ]($repo_root_style)\
[$path]($style)\
[ ]($style)\
([]($style)[ $read_only ]($read_only_style))"""
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "󰘬"
style = "fg:lc_mint bg:def_mint"
format = "[ $symbol $branch ]($style)"

[shell]
style = "fg:def_green bg:lc_green"
bash_indicator = "[ ]($style)"
fish_indicator = "[󰈺 ]($style)"
zsh_indicator = "[]($style)"
powershell_indicator = "[󰨊 ]"
cmd_indicator = "[ ]($style)"
unknown_indicator = "[]($style)"
format = "[ $indicator ]($style)"
disabled = false

[cmd_duration]
min_time = 25
style = "fg:lc_yellow bg:def_yellow"
format = "[ 󱫑 $duration ]($style)"

# RIGHT ALIGNED PROMPT

[status]
symbol = "[✘ ](fg:def_red bg:lc)"
success_symbol = "[✔ ](fg:def_green bg:lc)"
format = "$symbol"
disabled = false

[memory_usage]
threshold = 75
style = "fg:lc_orange bg:def_orange"
symbol = " 󰍛 "
format = "[$symbol$ram_pct ]($style)"
disabled = false

[custom.directory]
command = """basename $(eval "git rev-parse --show-toplevel")"""
require_repo = true
when = "true"
symbol = " "
style = "fg:def_red bg:lc_red"
format = "[ $symbol]($style)[$output ](fg:alt_red bg:lc_red)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:lc_pink bg:def_pink"
format = "[ 󱑎 $time]($style)"

# CHARACTER
[character]
success_symbol = "[❯](bold def_green)"
error_symbol = "[❯](bold def_red)"
